<?php

/**
 * Basemember_type
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $type_name
 * @property varchar $description
 * @property Doctrine_Collection $application
 * @property Doctrine_Collection $member
 * @property Doctrine_Collection $survey
 * @property Doctrine_Collection $survey_membertype
 * @property Doctrine_Collection $resource
 * @property Doctrine_Collection $resource_membertype
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method varchar             getTypeName()            Returns the current record's "type_name" value
 * @method varchar             getDescription()         Returns the current record's "description" value
 * @method Doctrine_Collection getApplication()         Returns the current record's "application" collection
 * @method Doctrine_Collection getMember()              Returns the current record's "member" collection
 * @method Doctrine_Collection getSurvey()              Returns the current record's "survey" collection
 * @method Doctrine_Collection getSurveyMembertype()    Returns the current record's "survey_membertype" collection
 * @method Doctrine_Collection getResource()            Returns the current record's "resource" collection
 * @method Doctrine_Collection getResourceMembertype()  Returns the current record's "resource_membertype" collection
 * @method member_type         setId()                  Sets the current record's "id" value
 * @method member_type         setTypeName()            Sets the current record's "type_name" value
 * @method member_type         setDescription()         Sets the current record's "description" value
 * @method member_type         setApplication()         Sets the current record's "application" collection
 * @method member_type         setMember()              Sets the current record's "member" collection
 * @method member_type         setSurvey()              Sets the current record's "survey" collection
 * @method member_type         setSurveyMembertype()    Sets the current record's "survey_membertype" collection
 * @method member_type         setResource()            Sets the current record's "resource" collection
 * @method member_type         setResourceMembertype()  Sets the current record's "resource_membertype" collection
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basemember_type extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('member_type');
        $this->hasColumn('id', 'integer', 2, array(
             'type' => 'integer',
             'size' => 2,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('type_name', 'varchar', 45, array(
             'type' => 'varchar',
             'unique' => true,
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('description', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('application', array(
             'local' => 'id',
             'foreign' => 'member_type_id'));

        $this->hasMany('member', array(
             'local' => 'id',
             'foreign' => 'member_type_id'));

        $this->hasMany('survey', array(
             'refClass' => 'survey_membertype',
             'local' => 'member_type_id',
             'foreign' => 'survey_id'));

        $this->hasMany('survey_membertype', array(
             'local' => 'id',
             'foreign' => 'member_type_id'));

        $this->hasMany('resource', array(
             'refClass' => 'resource_membertype',
             'local' => 'member_type_id',
             'foreign' => 'resource_id'));

        $this->hasMany('resource_membertype', array(
             'local' => 'id',
             'foreign' => 'member_type_id'));
    }
}