<?php

/**
 * Baseevent_type
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $type_name
 * @property varchar $description
 * @property Doctrine_Collection $calendar_event
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method varchar             getTypeName()       Returns the current record's "type_name" value
 * @method varchar             getDescription()    Returns the current record's "description" value
 * @method Doctrine_Collection getCalendarEvent()  Returns the current record's "calendar_event" collection
 * @method event_type          setId()             Sets the current record's "id" value
 * @method event_type          setTypeName()       Sets the current record's "type_name" value
 * @method event_type          setDescription()    Sets the current record's "description" value
 * @method event_type          setCalendarEvent()  Sets the current record's "calendar_event" collection
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseevent_type extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('event_type');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'size' => 4,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('type_name', 'varchar', 100, array(
             'type' => 'varchar',
             'notnull' => true,
             'unique' => true,
             'length' => 100,
             ));
        $this->hasColumn('description', 'varchar', 400, array(
             'type' => 'varchar',
             'notnull' => false,
             'length' => 400,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('calendar_event', array(
             'local' => 'id',
             'foreign' => 'event_type_id'));
    }
}