<?php

/**
 * Baseevent_file
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $event_id
 * @property varchar $file_name
 * @property varchar $photo_title
 * @property integer $display_order
 * @property calendar_event $calendar_event
 * 
 * @method integer        getId()             Returns the current record's "id" value
 * @method integer        getEventId()        Returns the current record's "event_id" value
 * @method varchar        getFileName()       Returns the current record's "file_name" value
 * @method varchar        getPhotoTitle()     Returns the current record's "photo_title" value
 * @method integer        getDisplayOrder()   Returns the current record's "display_order" value
 * @method calendar_event getCalendarEvent()  Returns the current record's "calendar_event" value
 * @method event_file     setId()             Sets the current record's "id" value
 * @method event_file     setEventId()        Sets the current record's "event_id" value
 * @method event_file     setFileName()       Sets the current record's "file_name" value
 * @method event_file     setPhotoTitle()     Sets the current record's "photo_title" value
 * @method event_file     setDisplayOrder()   Sets the current record's "display_order" value
 * @method event_file     setCalendarEvent()  Sets the current record's "calendar_event" value
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseevent_file extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('event_file');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'size' => 8,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('event_id', 'integer', 8, array(
             'type' => 'integer',
             'size' => 8,
             'unsigned' => true,
             'notnull' => false,
             'length' => 8,
             ));
        $this->hasColumn('file_name', 'varchar', 200, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('photo_title', 'varchar', 400, array(
             'type' => 'varchar',
             'notnull' => false,
             'length' => 400,
             ));
        $this->hasColumn('display_order', 'integer', 2, array(
             'type' => 'integer',
             'size' => 2,
             'notnull' => false,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('calendar_event', array(
             'local' => 'event_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}