<?php

/**
 * Basequestion_category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $category_name
 * @property integer $parent_category_id
 * @property Doctrine_Collection $question_bank
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method varchar             getCategoryName()       Returns the current record's "category_name" value
 * @method integer             getParentCategoryId()   Returns the current record's "parent_category_id" value
 * @method Doctrine_Collection getQuestionBank()       Returns the current record's "question_bank" collection
 * @method question_category   setId()                 Sets the current record's "id" value
 * @method question_category   setCategoryName()       Sets the current record's "category_name" value
 * @method question_category   setParentCategoryId()   Sets the current record's "parent_category_id" value
 * @method question_category   setQuestionBank()       Sets the current record's "question_bank" collection
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basequestion_category extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('question_category');
        $this->hasColumn('id', 'integer', 2, array(
             'type' => 'integer',
             'size' => 2,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('category_name', 'varchar', 255, array(
             'type' => 'varchar',
             'unique' => true,
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('parent_category_id', 'integer', 2, array(
             'type' => 'integer',
             'size' => 2,
             'unsigned' => true,
             'notnull' => false,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('question_bank', array(
             'local' => 'id',
             'foreign' => 'category_id'));
    }
}