<?php

/**
 * Basesurvey_question
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $survey_id
 * @property integer $parent_question_id
 * @property integer $question_id
 * @property boolean $mandatory
 * @property integer $page_id
 * @property boolean $disabled
 * @property integer $display_order
 * @property survey $survey
 * @property question_bank $question_bank
 * @property question_bank $parent_question
 * @property Doctrine_Collection $survey_data
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method integer             getSurveyId()           Returns the current record's "survey_id" value
 * @method integer             getParentQuestionId()   Returns the current record's "parent_question_id" value
 * @method integer             getQuestionId()         Returns the current record's "question_id" value
 * @method boolean             getMandatory()          Returns the current record's "mandatory" value
 * @method integer             getPageId()             Returns the current record's "page_id" value
 * @method boolean             getDisabled()           Returns the current record's "disabled" value
 * @method integer             getDisplayOrder()       Returns the current record's "display_order" value
 * @method survey              getSurvey()             Returns the current record's "survey" value
 * @method question_bank       getQuestionBank()       Returns the current record's "question_bank" value
 * @method question_bank       getParentQuestion()     Returns the current record's "parent_question" value
 * @method Doctrine_Collection getSurveyData()         Returns the current record's "survey_data" collection
 * @method survey_question     setId()                 Sets the current record's "id" value
 * @method survey_question     setSurveyId()           Sets the current record's "survey_id" value
 * @method survey_question     setParentQuestionId()   Sets the current record's "parent_question_id" value
 * @method survey_question     setQuestionId()         Sets the current record's "question_id" value
 * @method survey_question     setMandatory()          Sets the current record's "mandatory" value
 * @method survey_question     setPageId()             Sets the current record's "page_id" value
 * @method survey_question     setDisabled()           Sets the current record's "disabled" value
 * @method survey_question     setDisplayOrder()       Sets the current record's "display_order" value
 * @method survey_question     setSurvey()             Sets the current record's "survey" value
 * @method survey_question     setQuestionBank()       Sets the current record's "question_bank" value
 * @method survey_question     setParentQuestion()     Sets the current record's "parent_question" value
 * @method survey_question     setSurveyData()         Sets the current record's "survey_data" collection
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basesurvey_question extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('survey_question');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'size' => 8,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('survey_id', 'integer', 4, array(
             'type' => 'integer',
             'size' => 4,
             'unsigned' => true,
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('parent_question_id', 'integer', 4, array(
             'type' => 'integer',
             'size' => 4,
             'unsigned' => true,
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('question_id', 'integer', 4, array(
             'type' => 'integer',
             'size' => 4,
             'unsigned' => true,
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('mandatory', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('page_id', 'integer', 1, array(
             'type' => 'integer',
             'size' => 1,
             'notnull' => false,
             'length' => 1,
             ));
        $this->hasColumn('disabled', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('display_order', 'integer', 2, array(
             'type' => 'integer',
             'size' => 2,
             'notnull' => true,
             'default' => 0,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('survey', array(
             'local' => 'survey_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('question_bank', array(
             'local' => 'question_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('question_bank as parent_question', array(
             'local' => 'question_bank_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('survey_data', array(
             'local' => 'id',
             'foreign' => 'survey_question_id'));
    }
}