<?php

/**
 * Baseprogram_year
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $type_name
 * @property date $from_date
 * @property date $to_date
 * @property boolean $is_active
 * @property Doctrine_Collection $application
 * @property Doctrine_Collection $resource
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method varchar             getTypeName()    Returns the current record's "type_name" value
 * @method date                getFromDate()    Returns the current record's "from_date" value
 * @method date                getToDate()      Returns the current record's "to_date" value
 * @method boolean             getIsActive()    Returns the current record's "is_active" value
 * @method Doctrine_Collection getApplication() Returns the current record's "application" collection
 * @method Doctrine_Collection getResource()    Returns the current record's "resource" collection
 * @method program_year        setId()          Sets the current record's "id" value
 * @method program_year        setTypeName()    Sets the current record's "type_name" value
 * @method program_year        setFromDate()    Sets the current record's "from_date" value
 * @method program_year        setToDate()      Sets the current record's "to_date" value
 * @method program_year        setIsActive()    Sets the current record's "is_active" value
 * @method program_year        setApplication() Sets the current record's "application" collection
 * @method program_year        setResource()    Sets the current record's "resource" collection
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseprogram_year extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('program_year');
        $this->hasColumn('id', 'integer', 2, array(
             'type' => 'integer',
             'size' => 2,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('type_name', 'varchar', 45, array(
             'type' => 'varchar',
             'unique' => true,
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('from_date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('to_date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('application', array(
             'local' => 'id',
             'foreign' => 'program_year_id'));

        $this->hasMany('resource', array(
             'local' => 'id',
             'foreign' => 'program_year_id'));
    }
}