<?php

/**
 * Baseresource_membertype
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $resource_id
 * @property integer $member_type_id
 * @property resource $resource
 * @property member_type $member_type
 * 
 * @method integer             getResourceId()     Returns the current record's "resource_id" value
 * @method integer             getMemberTypeId()   Returns the current record's "member_type_id" value
 * @method resource            getResource()       Returns the current record's "resource" value
 * @method member_type         getMemberType()     Returns the current record's "member_type" value
 * @method resource_membertype setResourceId()     Sets the current record's "resource_id" value
 * @method resource_membertype setMemberTypeId()   Sets the current record's "member_type_id" value
 * @method resource_membertype setResource()       Sets the current record's "resource" value
 * @method resource_membertype setMemberType()     Sets the current record's "member_type" value
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseresource_membertype extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('resource_membertype');
        $this->hasColumn('resource_id', 'integer', 4, array(
             'type' => 'integer',
             'size' => 4,
             'unsigned' => true,
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('member_type_id', 'integer', 2, array(
             'type' => 'integer',
             'size' => 2,
             'unsigned' => true,
             'notnull' => false,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('resource', array(
             'local' => 'resource_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('member_type', array(
             'local' => 'member_type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}