<?php

/**
 * Basequestion_option
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $question_id
 * @property varchar $option_value
 * @property varchar $option_text
 * @property boolean $pre_selected
 * @property integer $display_order
 * @property question_bank $question_bank
 * 
 * @method integer         getId()            Returns the current record's "id" value
 * @method integer         getQuestionId()    Returns the current record's "question_id" value
 * @method varchar         getOptionValue()   Returns the current record's "option_value" value
 * @method varchar         getOptionText()    Returns the current record's "option_text" value
 * @method boolean         getPreSelected()   Returns the current record's "pre_selected" value
 * @method integer         getDisplayOrder()  Returns the current record's "display_order" value
 * @method question_bank   getQuestionBank()  Returns the current record's "question_bank" value
 * @method question_option setId()            Sets the current record's "id" value
 * @method question_option setQuestionId()    Sets the current record's "question_id" value
 * @method question_option setOptionValue()   Sets the current record's "option_value" value
 * @method question_option setOptionText()    Sets the current record's "option_text" value
 * @method question_option setPreSelected()   Sets the current record's "pre_selected" value
 * @method question_option setDisplayOrder()  Sets the current record's "display_order" value
 * @method question_option setQuestionBank()  Sets the current record's "question_bank" value
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basequestion_option extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('question_option');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'size' => 4,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('question_id', 'integer', 4, array(
             'type' => 'integer',
             'size' => 4,
             'unsigned' => true,
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('option_value', 'varchar', 45, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('option_text', 'varchar', 300, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 300,
             ));
        $this->hasColumn('pre_selected', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('display_order', 'integer', 1, array(
             'type' => 'integer',
             'size' => 1,
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('question_bank', array(
             'local' => 'question_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}