<?php

/**
 * Basequestion_bank
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property question_bank $ParentQuestion
 * @property question_category $question_category
 * @property Doctrine_Collection $question_bank
 * @property Doctrine_Collection $question_option
 * @property Doctrine_Collection $survey_question
 * @property Doctrine_Collection $survey_data
 * 
 * @method integer             getCategoryId()        Returns the current record's "category_id" value
 * @method question_bank       getParentQuestion()    Returns the current record's "ParentQuestion" value
 * @method question_category   getQuestionCategory()  Returns the current record's "question_category" value
 * @method Doctrine_Collection getQuestionBank()      Returns the current record's "question_bank" collection
 * @method Doctrine_Collection getQuestionOption()    Returns the current record's "question_option" collection
 * @method Doctrine_Collection getSurveyQuestion()    Returns the current record's "survey_question" collection
 * @method Doctrine_Collection getSurveyData()        Returns the current record's "survey_data" collection
 * @method question_bank       setCategoryId()        Sets the current record's "category_id" value
 * @method question_bank       setParentQuestion()    Sets the current record's "ParentQuestion" value
 * @method question_bank       setQuestionCategory()  Sets the current record's "question_category" value
 * @method question_bank       setQuestionBank()      Sets the current record's "question_bank" collection
 * @method question_bank       setQuestionOption()    Sets the current record's "question_option" collection
 * @method question_bank       setSurveyQuestion()    Sets the current record's "survey_question" collection
 * @method question_bank       setSurveyData()        Sets the current record's "survey_data" collection
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basequestion_bank extends question
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('question_bank');
        $this->hasColumn('category_id', 'integer', 2, array(
             'type' => 'integer',
             'size' => 2,
             'notnull' => false,
             'unsigned' => true,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('question_bank as ParentQuestion', array(
             'local' => 'parent_question_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('question_category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('question_bank', array(
             'local' => 'id',
             'foreign' => 'parent_question_id'));

        $this->hasMany('question_option', array(
             'local' => 'id',
             'foreign' => 'question_id'));

        $this->hasMany('survey_question', array(
             'local' => 'id',
             'foreign' => 'question_id'));

        $this->hasMany('survey_data', array(
             'local' => 'id',
             'foreign' => 'question_bank_id'));
    }
}