<?php

/**
 * Basesurvey_membertype
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $survey_id
 * @property integer $member_type_id
 * @property survey $survey
 * @property member_type $member_type
 * 
 * @method integer           getSurveyId()       Returns the current record's "survey_id" value
 * @method integer           getMemberTypeId()   Returns the current record's "member_type_id" value
 * @method survey            getSurvey()         Returns the current record's "survey" value
 * @method member_type       getMemberType()     Returns the current record's "member_type" value
 * @method survey_membertype setSurveyId()       Sets the current record's "survey_id" value
 * @method survey_membertype setMemberTypeId()   Sets the current record's "member_type_id" value
 * @method survey_membertype setSurvey()         Sets the current record's "survey" value
 * @method survey_membertype setMemberType()     Sets the current record's "member_type" value
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basesurvey_membertype extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('survey_membertype');
        $this->hasColumn('survey_id', 'integer', 4, array(
             'type' => 'integer',
             'size' => 4,
             'unsigned' => true,
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('member_type_id', 'integer', 2, array(
             'type' => 'integer',
             'size' => 2,
             'unsigned' => true,
             'notnull' => false,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('survey', array(
             'local' => 'survey_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('member_type', array(
             'local' => 'member_type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}