default:
  http_metas:
    content-type: text/html

  metas:
    title:         Best Buddies Admin
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [backend/main.css, ui-lightness/jquery-ui-1.10.0.custom.min.css]

  javascripts:    [jquery-1.9.0.min.js, jquery-ui-1.10.0.custom/js/jquery-ui-1.10.0.custom.min.js]

  has_layout:     true
  layout:         layout
