<?php

/**
 * applicationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class applicationTable extends Doctrine_Table
{
    const STATUS_PENDING = 1;
    const STATUS_PROCESSING = 2;
    const STATUS_APPROVED = 3;
    const STATUS_REJECTED = 4;
    
    static $APPLICATION_STATUS_VALUES = array
    (
        self::STATUS_PENDING=>"Pending",
        self::STATUS_PROCESSING=>"Processing",
        self::STATUS_APPROVED=>"Approved",
        self::STATUS_REJECTED=>"Rejected"
    );        
    
    
    /**
     * Returns an instance of this class.
     *
     * @return object applicationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('application');
    }
}