<?php

/**
 * calendar_eventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class calendar_eventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object calendar_eventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('calendar_event');
    }
    
    public static function getEventListForPeriod($from_date, $to_date, $member_type = false)
    {
        $query = self::getInstance()->createQuery('ce');
        
        $query->addWhere('ce.from_date >= ?', $from_date." 00:00:00");
        $query->addWhere('ce.to_date <= ?', $to_date." 23:59:59");
        $query->addWhere('ce.status <> ?', 3);
        $query->orderBy('ce.from_date asc');
        
        if($member_type)
        {
            
        }
        
        return $query->execute();
    }
}