<?php

/**
 * event_fileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class event_fileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object event_fileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('event_file');
    }
}