<?php

/**
 * event_memberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class event_memberTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object event_memberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('event_member');
    }
}