<?php

/**
 * event_typeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class event_typeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object event_typeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('event_type');
    }
}