<?php

/**
 * program_yearTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class program_yearTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object program_yearTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('program_year');
    }
}