<?php

/**
 * program_year
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class program_year extends Baseprogram_year
{
    public function __toString() {
        if($this->getTypeName())
        {
            return $this->getTypeName();
        }
        
        return "";
    }
}