<?php

/**
 * question_bankTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class question_bankTable extends questionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return question_bankTable question_bankTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('question_bank');
    }
    
    public function getPickListQuery($category_id = false)
    {
        $q = $this->createQuery('qb')
                    ->addWhere('qb.disabled <> 1');
        
        if($category_id)
            $q->addWhere ('qb.category_id = ?', $category_id);
        
        return $q;
    }
    
     public function getQuestionGroupsQuery()
    {
        return $this->createQuery('q')
                ->addWhere('q.answer_type = ?', self::ANSWER_TYPE_QUESTION_GROUP)
                ->orderBy('q.question_text');
        
        
    }
}