<?php

/**
 * question_categoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class question_categoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object question_categoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('question_category');
    }
}