<?php

/**
 * question_category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class question_category extends Basequestion_category
{
    public function __toString() {
        if( ($name = $this->getCategoryName()) )
            return $name;
        
        return "";
    }
}