<?php

/**
 * reminderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class reminderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object reminderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('reminder');
    }
}