<?php

/**
 * resource_membertypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class resource_membertypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object resource_membertypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('resource_membertype');
    }
}