<?php

/**
 * site_pageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class site_pageTable extends Doctrine_Table
{    
    const PAGE_STATUS_PUBLISHED = 1;
    const PAGE_STATUS_UNPUBLISHED = 2;
    
    static $page_status_choices = array(        
        self::PAGE_STATUS_UNPUBLISHED=>"UnPublished",
        self::PAGE_STATUS_PUBLISHED=>"Published",        
    );
    
    /**
     * Returns an instance of this class.
     *
     * @return object site_pageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('site_page');
    }
}