<?php

/**
 * site_page
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class site_page extends Basesite_page
{
    public function getStatusName()
    {
        if($this->getStatus())
        {
            return site_pageTable::$page_status_choices[$this->getStatus()];
        }
        else
            return "UnPublished";
        
    }
    
    public function __toString() {
        if($this->getTitle())
            return $this->getTitle();
        else {
            return "";
        }
    }
}