<?php

/**
 * survey_questionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class survey_questionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object survey_questionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('survey_question');
    }
    
    public static function getLastPageId($survey_id)
    {
        $results = self::getInstance()
                ->createQuery('sq')
                ->select('0 as idx, max(sq.page_id)')
                ->addWhere('sq.survey_id = ?', $survey_id)
                ->execute(array(), 'key_value_pair');
        
        if($results)
            return $results[0];
        else
            return 0;
    }
}