<?php

/**
 * survey_dataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class survey_dataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object survey_dataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('survey_data');
    }
}