<?php

/**
 * survey_membertypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class survey_membertypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object survey_membertypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('survey_membertype');
    }
}