<?php

/**
 * survey
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class survey extends Basesurvey
{
    public function getStatusName()
    {
        if($this->getStatus())
        {
            return surveyTable::$SURVEY_STATUS_LIST[$this->getStatus()];
        }
        return "";
    }
}