<?php

/**
 * surveyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class surveyTable extends Doctrine_Table
{
    const SURVEY_STATUS_SELECT = 0;
    const SURVEY_STATUS_PUBLISHED = 1;
    const SURVEY_STATUS_UNPUBLISHED = 2;
    
    public static $SURVEY_STATUS_LIST = array(
        self::SURVEY_STATUS_SELECT=>"Select",
        self::SURVEY_STATUS_PUBLISHED=>"Published",
        self::SURVEY_STATUS_UNPUBLISHED=>"UnPublished"
    );
    
    /**
     * Returns an instance of this class.
     *
     * @return object surveyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('survey');
    }
}