<?php

/**
 * survey_submission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class survey_submission extends Basesurvey_submission
{
    public function getStatusName()
    {
        if($this->getStatus())
        {
            return survey_submissionTable::$STATUS_CHOICES[$this->getStatus()];
        }
        return "Pending";
    }
}