<?php

/**
 * survey_submissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class survey_submissionTable extends Doctrine_Table
{
    const STATUS_PENDING  = 1;
    const STATUS_COMPLETE = 2;
    
    public static $STATUS_CHOICES = array(
        self::STATUS_PENDING=>"Pending",
        self::STATUS_COMPLETE=>"Complete",
    );
    
    /**
     * Returns an instance of this class.
     *
     * @return object survey_submissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('survey_submission');
    }
}