<?php

/**
 * survey_invitationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class survey_invitationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object survey_invitationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('survey_invitation');
    }
}