## YAML Template.
editSuccess:
  javascripts: [ tinymce/tiny_mce_src.js ]
newSuccess:  
  javascripts: [ tinymce/tiny_mce_src.js ]  
calendarSuccess:
  metas:
    title: Event Calendar
  layout: calendar
  stylesheets:
    - /js/wdCalendar/wdCalendar/css/dailog.css
    - /js/wdCalendar/wdCalendar/css/calendar.css
    - /js/wdCalendar/wdCalendar/css/dp.css
    - /js/wdCalendar/wdCalendar/css/alert.css
    - /js/wdCalendar/wdCalendar/css/main.css
  javascripts: 
    - -*        
    - jquery-1.6.2.min.js
    - wdCalendar/wdCalendar/src/Plugins/Common.js
    - wdCalendar/wdCalendar/src/Plugins/datepicker_lang_US.js
    - wdCalendar/wdCalendar/src/Plugins/jquery.datepicker.js
    - wdCalendar/wdCalendar/src/Plugins/jquery.alert.js
    - wdCalendar/wdCalendar/src/Plugins/jquery.ifrmdailog.js
    - wdCalendar/wdCalendar/src/Plugins/wdCalendar_lang_US.js
    - wdCalendar/wdCalendar/src/Plugins/jquery.calendar.js
    - jquery-ui-1.10.0.custom/js/jquery-ui-1.10.0.custom.min.js