generator:
  class: sfDoctrineGenerator
  param:
    model_class:           member
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          member
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    
        display: [ first_name, last_name, email_address, username, password, password_again ]
        actions: 
          _save: ~ 
      edit:    ~
      new:     ~
