<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/03/25 22:36:51

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=BestBuddies',
  'username' => 'root',
  'password' => 'admin',
  'attributes' => 
  array (
    'tblname_format' => 'bbd_%s',
  ),
  'name' => 'doctrine',
)),);
