<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/03/25 22:37:02
sfConfig::add(array(
  'mod_calendar_event_enabled' => true,
  'mod_calendar_event_view_class' => 'sfPHP',
));
