<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/03/25 22:36:52
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'member',
    ),
  ),
);
