<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/03/25 22:44:32
sfConfig::add(array(
  'app_datagrid_date_format' => 'd/m/Y',
  'app_datagrid_datetime_format' => 'd/m/Y à H:i:s',
  'app_datagrid_images_dir' => '/sfDatagridPlugin/img/',
  'app_datagrid_class_for_foreign' => 'sfWidgetFormDoctrineSelect',
  'app_datagrid_jsframwork' => 'jquery',
  'app_datagrid_text_novalueinrows' => 'No Records Found.',
  'app_datagrid_text_search' => 'Search',
  'app_datagrid_text_reset' => 'Reset',
  'app_datagrid_text_validate' => 'Validate',
  'app_datagrid_text_page' => 'Page',
  'app_datagrid_text_defaultview' => '',
  'app_datagrid_label_null' => 'Date Null',
  'app_datagrid_text_numberofrecords' => 'Number of Records',
  'app_datagrid_text_loading' => 'Searching..',
  'app_datagrid_text_from' => 'From',
  'app_datagrid_text_to' => 'To',
  'app_datagrid_insert_pager_bottom' => true,
  'app_datagrid_freezepanes' => false,
));
